# ############################################################################ #
#                                 NETWORKS                                     #
# ############################################################################ #
networks:
  ft_test:
    driver: bridge

# ############################################################################ #
#                                 SERVICES                                     #
# ############################################################################ #
services:

  mysql: # Port 3004
    container_name: mysql
    build: ./containers/mysql/.
    networks:
        - ft_test

  jwt: # Port 3003
    container_name: jwt
    build: ./containers/jwt/.
    networks:
        - ft_test

  pong: # Port 3002
    container_name: pong
    build: ./containers/pong/
    networks:
        - ft_test

  backend: # Port 3001
    container_name: backend
    build: ./containers/backend/.
    networks:
        - ft_test
    depends_on:
      - mysql
      - jwt
      - pong

  frontend: # Port 3000
    container_name: frontend
    build: ./containers/frontend/.
    ports:
      - 3000:3000
    networks:
        - ft_test
    depends_on:
      - backend
